name: run_unit_tests

on:
  push:
    branches: master
    paths:
      - src/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
        env:
          CI: true
